color0 #4a454b
color1 #ffb4ab
color2 #cfc2d5
color3 #ccc4cc
color4 #ddbfc6
color5 #cfc2d5
color6 #ccc4cc
color7 #e6e1e2
color8 #958f95
color9 #ffb4ab
color10 #cfc2d5
color11 #ccc4cc
color12 #ddbfc6
color13 #cfc2d5
color14 #ccc4cc
color15 #e6e1e2

cursor                #e6e1e2
cursor_text_color     #141314
background            #141314
foreground            #e6e1e2
selection_foreground  #ccc4cb
selection_background  #4a454b
active_border_color   #cfc2d5
inactive_border_color #4a454b
url_color             #cfc2d5

active_tab_foreground   #352d3b
active_tab_background   #cfc2d5
inactive_tab_foreground #ccc4cb
inactive_tab_background #4a454b
cursor_trail_color      #ccc4cb
